### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jsteggink** [hmsonline/cassandra-triggers#27]
Hi,

I tried installing cassandra-triggers according to the installation manual. However when I run cassandra I get "Segmentation fault".

I'm using Cassandra 1.0.7.

J.

**Comment by ptgoetz** [comment]
Hi J.,

Can you include a stacktrace or log snippet leading up to the segfault?

When did it occur?

The fact that you got a segfault points to something running native (I.e.
outside of the JVM).

Can you run C\* without triggers?
- Taylor
  On Mar 18, 2012 6:02 PM, "jsteggink" <
  reply@reply.github.com>
  wrote:

**Comment by jsteggink** [comment]
Hi Taylor,

After searching the internet I found the problem. It's a bug in OpenJDK. 
I switched to Sun JDK and now it works.

Cheers,

Jeroen
