### ISSUE TITLE
Configuration Wiki page no longer reflects actual schema

### ISSUE THREAD

**Issue by andrewswan** [hmsonline/cassandra-triggers#42]
[Commit 98b3720](https://github.com/hmsonline/cassandra-triggers/commit/98b372001feba49bc8e54b79428b772d71d6ee9d) changed the "triggers" schema so that each Cassandra node has its own CFs for the commit and error logs. However the Configuration wiki page:
- still says that there is a single CommitLog column family, and
- doesn't mention the error log.

**Comment by boneill42** [comment]
Updated the wiki appropriately.  Also added a GettingStarted page to make things more clear.
https://github.com/hmsonline/cassandra-triggers/wiki/GettingStarted

**Comment by andrewswan** [comment]
Thanks; I did some minor tidying of the wiki pages.
