### ISSUE TITLE
Dodgy "while" condition in TriggerExecutionThread#run

### ISSUE THREAD

**Issue by andrewswan** [hmsonline/cassandra-triggers#43]
The method c.h.c.t.TriggerExecutionThread.run() contains this check:

```
while (!((logEntry = workQueue.take()).equals("DONE"))) {
```

The problem is that logEntry is a LogEntry instance, while "DONE" is a String, so the two will never be equal under any circumstances.

This issue has existed since this class was added by [commit 00a922b0a1](https://github.com/hmsonline/cassandra-triggers/commit/00a922b0a14045bb0d6cecf5ae6cf02e45c4962e).

I'd happily submit a pull request to fix it, but I don't know the intended behaviour, nor whether anyone is relying on the current broken behaviour.

**Comment by boneill42** [comment]
Wow, really dodgy!  I'll take a look and fix.

**Comment by boneill42** [comment]
Fixed in release 1.0.0
